*** empty log message ***
git-svn-id: file:///usr/local/Singular/svn/trunk@2028 2c84dea3-7e68-4137-9b89-c4e89433aadc

diff --git a/Singular/configure b/Singular/configure
--- a/Singular/configure
+++ b/Singular/configure
@@ -1175,7 +1175,7 @@ echo "configure:1173: checking for flex" >&5
 else
   if (flex --version >/dev/null 2>&1)
   then
-    if (flex --version | egrep "[2-9]\.[4-9]\." >/dev/null 2>&1) 
+    if (flex --version | egrep "[2-9]\.[4-9]" >/dev/null 2>&1) 
     then
       ac_cv_prog_flex=flex
     fi
@@ -1188,7 +1188,7 @@ fi
     LEX=flex
     
   else
-    { echo "configure: error: can not find flex with version greater 2.5" 1>&2; exit 1; }
+    { echo "configure: error: can not find flex with version greater 2.4" 1>&2; exit 1; }
   fi
 elif test "${with_lex}" = no; then
   echo "configure: warning: building without lex -- make might fail" 1>&2
