*hannes: flex test
git-svn-id: file:///usr/local/Singular/svn/trunk@10300 2c84dea3-7e68-4137-9b89-c4e89433aadc

diff --git a/Singular/configure b/Singular/configure
--- a/Singular/configure
+++ b/Singular/configure
@@ -1536,7 +1536,7 @@ fi
     LEX=flex
     
   else
-    { echo "configure: error: can not find flex with version greater 2.4" 1>&2; exit 1; }
+    { echo "configure: error: can not find flex with version 2.4.5-2.5.4" 1>&2; exit 1; }
   fi
 elif test "${with_lex}" = no; then
   echo "configure: warning: building without lex -- make might fail" 1>&2
