*hannes: version 2-0-5
git-svn-id: file:///usr/local/Singular/svn/trunk@6992 2c84dea3-7e68-4137-9b89-c4e89433aadc

diff --git a/factory/configure b/factory/configure
--- a/factory/configure
+++ b/factory/configure
@@ -578,7 +578,7 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 #
 # Do not change version here!!!
 #
-factory_version="2.0.4"
+factory_version="2.0.5"
 factory_configuration="'$ac_configure_args' in `pwd`"
 
 #
@@ -1919,7 +1919,7 @@ EOF
  
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: C++ header files not found" 1>&2; exit 1; } 
+echo "configure: warning: C++ header files not found" 1>&2 
 fi
 done
 
