* small bug fixes
git-svn-id: file:///usr/local/Singular/svn/trunk@4567 2c84dea3-7e68-4137-9b89-c4e89433aadc

diff --git a/factory/configure b/factory/configure
--- a/factory/configure
+++ b/factory/configure
@@ -1821,7 +1821,7 @@ done
 
 fi
 
-for ac_hdr in stdio.h stdlib.h string.h time.h math.h omalloc.h
+for ac_hdr in stdio.h stdlib.h string.h time.h math.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
@@ -2039,6 +2039,47 @@ done
 
 fi
 
+for ac_hdr in omalloc.h
+do
+ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
+echo "configure:2047: checking for $ac_hdr" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 2052 "configure"
+#include "confdefs.h"
+#include <$ac_hdr>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:2057: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&6
+fi
+done
+
+
 # font-lock-trick: '
 
 #
@@ -2068,12 +2109,12 @@ fi
 # font-lock-trick: '
 
 echo $ac_n "checking for working const""... $ac_c" 1>&6
-echo "configure:2072: checking for working const" >&5
+echo "configure:2113: checking for working const" >&5
 if eval "test \"`echo '$''{'ac_cv_c_const'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2077 "configure"
+#line 2118 "configure"
 #include "confdefs.h"
 
 int main() {
@@ -2122,7 +2163,7 @@ ccp = (char const *const *) p;
 
 ; return 0; }
 EOF
-if { (eval echo configure:2126: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2167: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_const=yes
 else
@@ -2143,21 +2184,21 @@ EOF
 fi
 
 echo $ac_n "checking for inline""... $ac_c" 1>&6
-echo "configure:2147: checking for inline" >&5
+echo "configure:2188: checking for inline" >&5
 if eval "test \"`echo '$''{'ac_cv_c_inline'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_cv_c_inline=no
 for ac_kw in inline __inline__ __inline; do
   cat > conftest.$ac_ext <<EOF
-#line 2154 "configure"
+#line 2195 "configure"
 #include "confdefs.h"
 
 int main() {
 } $ac_kw foo() {
 ; return 0; }
 EOF
-if { (eval echo configure:2161: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2202: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_inline=$ac_kw; break
 else
@@ -2185,7 +2226,7 @@ esac
 
 # arithmetic shift
 echo $ac_n "checking whether your compiler does arithmetic shifts""... $ac_c" 1>&6
-echo "configure:2189: checking whether your compiler does arithmetic shifts" >&5
+echo "configure:2230: checking whether your compiler does arithmetic shifts" >&5
 if eval "test \"`echo '$''{'ac_cv_shift'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2193,11 +2234,11 @@ else
   ac_cv_shift=yes
 else
   cat > conftest.$ac_ext <<EOF
-#line 2197 "configure"
+#line 2238 "configure"
 #include "confdefs.h"
  int main() { if (-2 >> 1 == -1) exit(0); else exit(1); } 
 EOF
-if { (eval echo configure:2201: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2242: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_shift=yes
 else
@@ -2300,12 +2341,12 @@ if test "x$gmp_in_installation" = xyes; then
 fi
 
 echo $ac_n "checking whether to use omalloc""... $ac_c" 1>&6
-echo "configure:2304: checking whether to use omalloc" >&5
+echo "configure:2345: checking whether to use omalloc" >&5
 
 if test "$with_omalloc" = yes; then
   if test "$ac_cv_header_omalloc_h" != yes; then
     if test "$enable_omalloc" = yes; then
-       echo "configure: warning: did not find omalloc.h" 1>&2
+       warn_omalloc=yes
     else
        with_omalloc=no
     fi
@@ -2314,7 +2355,7 @@ else
   if test "$with_omalloc" != no; then
     if test "$enable_omalloc" = yes; then
       if test "$ac_cv_header_omalloc_h" != yes; then
-        echo "configure: warning: did not find omalloc.h" 1>&2
+        warn_omalloc=yes
       fi
       with_omalloc=yes
     else
@@ -2330,6 +2371,10 @@ EOF
   with_memman=no 
 fi
 echo "$ac_t""$with_omalloc" 1>&6
+if test "$warn_omalloc" = yes; then
+  echo "configure: warning: did not find omalloc.h -- install before compiling" 1>&2
+fi
+
     
 # memory manager
 if test "x$with_memman" != xno; then
