*hannes: NTL- 5.3.1
git-svn-id: file:///usr/local/Singular/svn/trunk@6910 2c84dea3-7e68-4137-9b89-c4e89433aadc

diff --git a/ntl/src/configure b/ntl/src/configure
--- a/ntl/src/configure
+++ b/ntl/src/configure
@@ -1,67 +1,96 @@
 #!/bin/sh
 
-for i in "$@"
-do
-   case $i in
-      CC=*) ;;
-      CXX=*) ;;
-      CFLAGS=*) ;;
-      CXXFLAGS=*) ;;
-      AR=*) ;;
-      ARFLAGS=*) ;;
-      RANLIB=*) ;;
-      LDFLAGS=*) ;;
-      LDFLAGS_CXX=*) ;;
-      LDLIBS=*) ;;
-      LDLIBS_CXX=*) ;;
-      CPPFLAGS=*) ;;
-      PREFIX=*) ;;
-      LIBDIR=*) ;;
-      INCLUDEDIR=*) ;;
-      DOCDIR=*) ;;
-      GMP_PREFIX=*) ;;
-      GMP_INCDIR=*) ;;
-      GMP_LIBDIR=*) ;;
-      NTL_STD_CXX=*) ;;
-      NTL_PSTD_NNS=*) ;;
-      NTL_PSTD_NHF=*) ;;
-      NTL_PSTD_NTN=*) ;;
-      NTL_GMP_LIP=*) ;;
-      NTL_GMP_HACK=*) ;;
-      NTL_CXX_ONLY=*) ;;
-      NTL_X86_FIX=*) ;;
-      NTL_NO_X86_FIX=*) ;;
-      NTL_AVOID_FLOAT=*) ;;
-      NTL_LONG_LONG=*) ;;
-      NTL_AVOID_BRANCHING=*) ;;
-      NTL_FFT_PIPELINE=*) ;;
-      NTL_TBL_REM=*) ;;
-      NTL_NO_INIT_TRANS=*) ;;
-      NTL_RANGE_CHECK=*) ;;
-      NTL_LONG_LONG_TYPE=*) ;;
-      WIZARD=*) ;;
-      -h) more ../doc/config.txt; exit 0 ;;
-      help) more ../doc/config.txt; exit 0 ;;
-      -help) more ../doc/config.txt; exit 0 ;;
-      --help) more ../doc/config.txt; exit 0 ;;
-      *) echo "error: unrecognized option $i"; exit 1 ;;
-   esac
-done
+if test $# -ne 0
+then 
 
-if make -s -f make.config "$@" > make.head 
-then
-   echo make.config OK
-else
-   cat make.head
-   exit 1
-fi
+   for i in "$@"
+   do
+      case $i in
+	 CC=*) ;;
+	 CXX=*) ;;
+	 CFLAGS=*) ;;
+	 CXXFLAGS=*) ;;
+	 AR=*) ;;
+	 ARFLAGS=*) ;;
+	 RANLIB=*) ;;
+	 LDFLAGS=*) ;;
+	 LDFLAGS_CXX=*) ;;
+	 LDLIBS=*) ;;
+	 LDLIBS_CXX=*) ;;
+	 CPPFLAGS=*) ;;
+	 PREFIX=*) ;;
+	 LIBDIR=*) ;;
+	 INCLUDEDIR=*) ;;
+	 DOCDIR=*) ;;
+	 GMP_PREFIX=*) ;;
+	 GMP_INCDIR=*) ;;
+	 GMP_LIBDIR=*) ;;
+	 NTL_STD_CXX=*) ;;
+	 NTL_PSTD_NNS=*) ;;
+	 NTL_PSTD_NHF=*) ;;
+	 NTL_PSTD_NTN=*) ;;
+	 NTL_GMP_LIP=*) ;;
+	 NTL_GMP_HACK=*) ;;
+	 NTL_CXX_ONLY=*) ;;
+	 NTL_X86_FIX=*) ;;
+	 NTL_NO_X86_FIX=*) ;;
+	 NTL_AVOID_FLOAT=*) ;;
+	 NTL_LONG_LONG=*) ;;
+	 NTL_AVOID_BRANCHING=*) ;;
+	 NTL_FFT_PIPELINE=*) ;;
+	 NTL_TBL_REM=*) ;;
+	 NTL_NO_INIT_TRANS=*) ;;
+	 NTL_CLEAN_INT=*) ;;
+	 NTL_CLEAN_PTR=*) ;;
+	 NTL_RANGE_CHECK=*) ;;
+	 NTL_LONG_LONG_TYPE=*) ;;
+	 WIZARD=*) ;;
+	 -h) more ../doc/config.txt; exit 0 ;;
+	 help) more ../doc/config.txt; exit 0 ;;
+	 -help) more ../doc/config.txt; exit 0 ;;
+	 --help) more ../doc/config.txt; exit 0 ;;
+	 *) echo "error: unrecognized option $i"; exit 1 ;;
+      esac
+   done
 
-if make -s -f flags.config "$@" > flags.sed
-then
-   echo flags.config OK
+   if make -s -f make.config "$@" > make.head 
+   then
+      echo make.config OK
+   else
+      cat make.head
+      exit 1
+   fi
+
+   if make -s -f flags.config "$@" > flags.sed
+   then
+      echo flags.config OK
+   else
+      cat flags.sed
+      exit 1
+   fi
+
 else
-   cat flags.sed
-   exit 1
+
+#  we special case $# == 0, because some shells do not handle
+#  the "$@" construction in the right way in this case.
+
+   if make -s -f make.config > make.head 
+   then
+      echo make.config OK
+   else
+      cat make.head
+      exit 1
+   fi
+
+   if make -s -f flags.config > flags.sed
+   then
+      echo flags.config OK
+   else
+      cat flags.sed
+      exit 1
+   fi
+   
+
 fi
 
 echo "writing makefile"
